### ISSUE TITLE
Can't set min_doc_count on date histogram aggregation

### ISSUE THREAD

**Issue by danjohnson95** [designmynight/laravel-elasticsearch#21]
When executing a *Date Histogram* aggregation, Elasticsearch will only return a bucket for each interval **if there is any data**.

To receive a bucket for days containing no data, the `min_doc_count` and `extended_bounds` must be specified.

https://www.elastic.co/guide/en/elasticsearch/guide/current/_returning_empty_buckets.html

**Comment by robbytaylor** [comment]
👍  I made a workaround to this, not realising it was even something ES could do

https://github.com/designmynight/spritz-api/blob/master/app/Collections/Aggregations/SalesByDateRange.php#L43
